### PR TITLE
Implement BIP38 encrypted passwords brute force cracking

### PR DESCRIPTION
**Pull request by ghallak**
@jeffersonn-1 I have only implemented CPU brute force cracking, please let me know if this works. I have tested this with the encrypted private keys from here https://github.com/bitcoin/bips/blob/master/bip-0038.mediawiki#Test_vectors

Usage example:
```
python3 btcrecover.py --bip38 --passwordlist docs/Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/passwordListTest_1.txt --dsw --enc-privkey 6PgNBNNzDkKdhkT6uJntUXwwzQV8Rr2tZcbkDcuC9DZRsS6AtHts4Ypo1j
```

### CODE REVIEW

**Comment by jeffersonn-1** [comment]
Looks really good. I'll be testing this today this afternoon. If all goes well, I will merge the commit by tomorrow for at least the CPU side of this.

**Comment by jeffersonn-1** [comment]
Hey I'm trying to run it but no matter what I throw at it, it doesn't seem to try more than one password against the wallet. For example, I'll do Someword%1,99d (1 through 99 digit decimal) and it will just go for one second and say list exhausted. Can you take another peek at this please?

**Comment by ghallak** [comment]
@jeffersonn-1 Can you please share the command you're using and what output are you getting?


Here's the command I'm using and its output (the file `docs/Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/passwordListTest_1.txt` does not have the correct password which is `MOLON LABE`):
```
$ python3 btcrecover.py --bip38 --passwordlist docs/Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/passwordListTest_1.txt --dsw --enc-privkey 6PgNBNNzDkKdhkT6uJntUXwwzQV8Rr2tZcbkDcuC9DZRsS6AtHts4Ypo1j

Starting btcrecover 1.3.0-Cryptoguide on Python 3.8.2 64-bit, 21-bit unicodes, 64-bit ints
Wallet difficulty: scrypt N, r, p = 16384, 8, 8 and scrypt N, r, p = 1024, 1, 1
Notice: Loading File:  docs/Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/passwordListTest_1.txt
Notice: Finished File:  docs/Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/passwordListTest_1.txt
2020-09-15 09:04:18 : Using 4 worker threads
Notice: Loading File:  docs/Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/passwordListTest_1.txt-----------------------------] 0:00:00, ETA:  --:--:--
Notice: Finished File:  docs/Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/passwordListTest_1.txt
21 of 21 [####################################################################################################################################################] 0:00:05, 
Password search exhausted
```

**Comment by jeffersonn-1** [comment]
It's processing any password entered into the script but it isn't processing the defined password variations. For example, %p should be any ASCII digit or symbol...if you do %p%p%p%p%p%p%p%p%p%p -- it should be trying quite a few million combinations (insane, I know). But it doesn't do that. Modify that file or create a password.txt file with the above and you'll see what I mean. Try examining the usage document - it goes into detail about the algorithmic functions -- those % short codes are not being processed (except perhaps literally?)

**Comment by ghallak** [comment]
I have created a new file called `passwords.txt` inside the `btcrecover` directory:

```
$ cat passwords.txt 
MOLON L%p%pE
```

Then I ran the following command from the `btcrecover` directory as well (I have added `--has-wildcards` flag to make sure that the passwords are not processed literally), and got  the following output:
```
$ python3 btcrecover.py --bip38 --passwordlist passwords.txt --has-wildcards --max-eta 200000000000000000000 --dsw --enc-privkey 6PgNBNNzDkKdhkT6uJntUXwwzQV8Rr2tZcbkDcuC9DZRsS6AtHts4Ypo1j

Starting btcrecover 1.3.0-Cryptoguide on Python 3.8.2 64-bit, 21-bit unicodes, 64-bit ints                                                                               
Wallet difficulty: scrypt N, r, p = 16384, 8, 8 and scrypt N, r, p = 1024, 1, 1                                                                                          
Notice: Loading File:  passwords.txt                                                                                                                                     
Notice: Finished File:  passwords.txt                                                                                                                                    
2020-09-16 10:40:56 : Using 4 worker threads                                                                                                                             
Notice: Loading File:  passwords.txt------------------------------------------------------------------------------------------------------------] 0:00:00, ETA:  --:--:--
3041 of 8836 [#############################################--------------------------------------------------------------------------------------] 0:13:58, ETA:  0:26:37
                                                                                                                                                                         
If this tool helped you to recover funds, please consider donating 1% of what you recovered, in your crypto of choice to:                                                
BTC: 37N7B7sdHahCXTcMJgEnHz7YmiR4bEqCrS                                                                                                                                  
BCH: qpvjee5vwwsv78xc28kwgd3m9mnn5adargxd94kmrt                                                                                                                          
LTC: M966MQte7agAzdCZe5ssHo7g9VriwXgyqM                                                                                                                                  
ETH: 0x72343f2806428dbbc2C11a83A1844912184b4243                                                                                                                          
                                                                                                                                                                         
Find me on Reddit @ https://www.reddit.com/user/Crypto-Guide                                                                                                             
                                                                                                                                                                         
You may also consider donating to Gurnec, who created and maintained this tool until late 2017 @ 3Au8ZodNHPei7MQiSVAWb7NB2yqsb48GW4                                      
                                                                                                                                                                         
Password found: 'MOLON LABE'
```

Are you sure you are adding the `--has-wildcards` flag to your command? Can you try the same command that I've posted above and see if it works?

There is only one line in the `passwords.txt` file, but the program is running over `8836` passwords because it's expanding both of the `%p` signs.

**Comment by jeffersonn-1** [comment]
Okay. I got that working. Now...can you or someone do the GPU acceleration side?

**Comment by jeffersonn-1** [comment]
So what would be a fair payout for this since it is not 100% done but only partially done?

**Comment by ghallak** [comment]
>Okay. I got that working. Now...can you or someone do the GPU acceleration side?

I can work on the GPU acceleration, but this can take a few more days.

> So what would be a fair payout for this since it is not 100% done but only partially done?

Can you send 1.0 ETH out of the 1.8 ETH? (that would be around ~ 55.56% of the total bounty)

**Comment by jeffersonn-1** [comment]
Okay. I can add a bit more ETH for the GPU then to make it a total of 2+ ETH. Give me a bit to jigger things around to make that work. Also ... I'll try to figure out how to do a partial payout today too. My key is at home and I'm out in the field but it is on my calendar to do.

Please keep me posted on the GPU progress. I now have ~20 computers (over 200 cores) cranking away at this.

**Comment by jeffersonn-1** [comment]
Sorry it took so long. Paid the bounty :) ... Another ~1 ETH to go for GPU support.

**Comment by ghallak** [comment]
@jeffersonn-1 I'm still experimenting with the GPU support in a different branch here https://github.com/ghallak/btcrecover/tree/bip38-cracking-gpu

I won't be able to get access to a good GPU before 2 or 3 days from now, so could you please pull that branch and test it on your machine if you have a working GPU. The GPU acceleration is enabled by adding `--enable-opencl` to the command.

The above command for CPU was:
```
python3 btcrecover.py \
  --dsw \
  --bip38 \
  --passwordlist docs/Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/passwordListTest_1.txt \
  --enc-privkey 6PgNBNNzDkKdhkT6uJntUXwwzQV8Rr2tZcbkDcuC9DZRsS6AtHts4Ypo1j

```

For GPU it becomes:
```
python3 btcrecover.py \
  --dsw \
  --enable-opencl \
  --bip38 \
  --passwordlist docs/Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/passwordListTest_1.txt \
  --enc-privkey 6PgNBNNzDkKdhkT6uJntUXwwzQV8Rr2tZcbkDcuC9DZRsS6AtHts4Ypo1j
```

Please modify the file `docs/Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/passwordListTest_1.txt` so that there is a large enough amount of passwords to try in order to see how faster the GPU implementation is compared to the CPU.

**Comment by jeffersonn-1** [comment]
@ghallak Are you saying that this PR includes GPU support? I didn't think to test GPU with this and I thought it was still outstanding?

**Comment by ghallak** [comment]
This PR does not include GPU support yet. I'm experimenting with GPU support on a different branch https://github.com/ghallak/btcrecover/tree/bip38-cracking-gpu. Please pull that branch and test the GPU support by adding `--enable-opencl` and let me know how fast did it get compared to running it on the CPU.

**Comment by jeffersonn-1** [comment]
I'm getting a random opencl_information not defined. Running Py 3.8 and I installed the latest OpenCL running an Nvidia 1080 with the latest OpenCL drivers. Any recommendations so that I can get OpenCL properly running so I can run some tests for you?

**Comment by ghallak** [comment]
>I'm getting a random opencl_information not defined

Can you please paste the exact command you used with the exact output that you got? Are you using Windows or Linux? Have you run any of the commands mentioned here https://github.com/jeffersonn-1/btcrecover/blob/master/docs/GPU_Acceleration.md#testing-your-system? These commands:
```
python3 -m btcrecover.test.test_passwords -v GPUTests
python3 -m btcrecover.test.test_passwords -v OpenCL_Tests
python3 -m btcrecover.test.test_seeds -v OpenCL_Tests
```
What output did you get for each for them?

**Comment by Karl483r** [comment]
Hi, a GPU implementation sounds very interesting. Thank you for your work. How many passwords can you check per second on your GPU(s)?

@jeffersonn-1  How many PW/s can you test on your 200 cores?

**Pull request merged**
